// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULklhZvoBuYaMIW14OKHq_MIOaHiPxU0',
    appId: '1:986954955333:web:76febdfecb7311a0e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    authDomain: 'senerity-3930a.firebaseapp.com',
    databaseURL: 'https://senerity-3930a-default-rtdb.firebaseio.com',
    storageBucket: 'senerity-3930a.appspot.com',
    measurementId: 'G-FRP7MYTV5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Py0049cS2-GSylLoKW6ivILFvdz5CJ0',
    appId: '1:986954955333:android:207449efef474a30e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    databaseURL: 'https://senerity-3930a-default-rtdb.firebaseio.com',
    storageBucket: 'senerity-3930a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdkeREBffwuIOANOU5HYVTmNmksCXNz8',
    appId: '1:986954955333:ios:3b9901cf3b5f1ec2e2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    databaseURL: 'https://senerity-3930a-default-rtdb.firebaseio.com',
    storageBucket: 'senerity-3930a.appspot.com',
    iosClientId: '986954955333-iu3033s05iocqughg3juf23fob9s3hmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.partnerr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdkeREBffwuIOANOU5HYVTmNmksCXNz8',
    appId: '1:986954955333:ios:5a77dc0820939c3ee2412c',
    messagingSenderId: '986954955333',
    projectId: 'senerity-3930a',
    databaseURL: 'https://senerity-3930a-default-rtdb.firebaseio.com',
    storageBucket: 'senerity-3930a.appspot.com',
    iosClientId: '986954955333-7j466rnlnteenatla13hp2q52pjmbogm.apps.googleusercontent.com',
    iosBundleId: 'com.example.partnerr.RunnerTests',
  );
}
